import { useMemo, useState } from "react";
import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronRight,
  CircleHelp,
  Clock3,
  Copy,
  FileCheck2,
  Leaf,
  MapPin,
  Menu,
  Navigation,
  PackageCheck,
  Recycle,
  Route as RouteIcon,
  ShieldCheck,
  Truck,
  Upload,
  Wifi,
  WifiOff,
  X,
  Zap,
} from "lucide-react";
import { toast } from "sonner";
import { SharedPickup, useEcovaData } from "@/contexts/EcovaDataContext";

type CollectorView = "overview" | "queue" | "routes" | "earnings" | "history";
type Sheet = "request" | "active" | "verify" | null;

function CollectorMark({ size = 28 }: { size?: number }) { return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 36 36" fill="none"><path d="M18 4.5C24.9 4.5 30.5 10.1 30.5 17" stroke="#0f172a" strokeWidth="2.8" strokeLinecap="round" /><path d="M30.5 17C30.5 23.9 24.9 29.5 18 29.5C11.1 29.5 5.5 23.9 5.5 17" stroke="#10b981" strokeWidth="2.8" strokeLinecap="round" /><path d="M5.5 17C5.5 10.1 11.1 4.5 18 4.5" stroke="#0f172a" strokeWidth="2.8" strokeLinecap="round" strokeDasharray="2 4" /><path d="M18 1.8L21.4 6.2L15.8 6.7" fill="#10b981" /><path d="M33.6 17L28.2 14.9L29.1 20.4" fill="#10b981" /><path d="M4 17L9.4 19.1L8.5 13.6" fill="#0f172a" /><circle cx="18" cy="17" r="3.2" fill="#10b981" /></svg>; }
function Kicker({ children }: { children: React.ReactNode }) { return <p className="col-kicker">{children}</p>; }

function Collector() {
  const { pickups, collectorOnline, setCollectorOnline, acceptPickup, markArrived, markCollected, verifyWeight, deliverToHub, confirmRecycling, collectorEarnings, notifications, syncStatus, dataError, isMutating } = useEcovaData();
  const [view, setView] = useState<CollectorView>("overview");
  const [sheet, setSheet] = useState<Sheet>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [mobileNav, setMobileNav] = useState(false);
  const [verifiedWeight, setVerifiedWeight] = useState(4.7);
  const [condition, setCondition] = useState<"Clean" | "Mostly clean" | "Mixed" | "Contaminated">("Clean");
  const [proofImageData, setProofImageData] = useState<string | undefined>();
  const [proofFileName, setProofFileName] = useState<string | undefined>();
  const selected = pickups.find((pickup) => pickup.id === selectedId) ?? null;
  const requests = pickups.filter((pickup) => pickup.status === "REQUESTED");
  const active = pickups.find((pickup) => ["ASSIGNED", "ARRIVED", "COLLECTED", "VERIFIED", "DELIVERED"].includes(pickup.status));
  const routeStops = pickups.filter((pickup) => pickup.status !== "RECYCLED").slice(0, 3);
  const setViewAndClose = (next: CollectorView) => { setView(next); setMobileNav(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const openRequest = (pickup: SharedPickup) => { setSelectedId(pickup.id); setSheet("request"); };
  const openActive = (pickup: SharedPickup) => { setSelectedId(pickup.id); setVerifiedWeight(pickup.verifiedWeight ?? Math.min(pickup.estimatedWeight, 4.7)); setProofImageData(undefined); setProofFileName(undefined); setSheet("active"); };
  const onProofSelected = (file: File) => { const reader = new FileReader(); reader.onload = () => { setProofImageData(String(reader.result)); setProofFileName(file.name); }; reader.readAsDataURL(file); };
  const completeVerification = async () => { if (!selected) return; const result = await verifyWeight(selected.id, verifiedWeight, condition, proofImageData); toast(`Verification recorded · +${result.rewardAmount} ECO`, { description: `${selected.id} is now verified and persisted.` }); setSheet(null); };
  const toggleOnline = async () => { await setCollectorOnline(!collectorOnline); toast(!collectorOnline ? "Collector online" : "Offline mode enabled"); };
  const viewNames: Record<CollectorView, string> = { overview: "Overview", queue: "Pickup Queue", routes: "Routes", earnings: "Earnings", history: "History" };
  const navItems: { key: CollectorView; label: string; icon: typeof Truck }[] = [{ key: "overview", label: "Overview", icon: Zap }, { key: "queue", label: "Pickup Queue", icon: PackageCheck }, { key: "routes", label: "Routes", icon: RouteIcon }, { key: "earnings", label: "Earnings", icon: FileCheck2 }, { key: "history", label: "History", icon: Clock3 }];

  return <div className="collector-app">
    <aside className={`collector-sidebar ${mobileNav ? "collector-sidebar-open" : ""}`}>
      <div className="col-brand"><a href="/" aria-label="Back to Ecova landing page"><CollectorMark size={30} /><span>ecova</span></a><div className="col-role">/ COLLECT</div></div>
      <div className="col-sidebar-label">WORKSPACE</div>
      <nav className="col-nav">{navItems.map(({ key, label, icon: Icon }) => <button key={key} className={view === key ? "col-nav-active" : ""} onClick={() => setViewAndClose(key)}><Icon size={16} /><span>{label}</span>{view === key && <i />}</button>)}</nav>
      <div className="col-bottom"><div className="col-sidebar-label">DEMO ROLE</div><button className="col-role-button" onClick={() => window.location.href = "/generator"}><span className="col-avatar"><CollectorMark size={16} /></span><span><b>Collector</b><small>Switch demo role</small></span><ChevronRight size={14} /></button><a href="/">← Back to public site</a></div>
    </aside>
    <main className="collector-main">
      <header className="collector-header"><button className="mobile-col-menu" onClick={() => setMobileNav((current) => !current)}>{mobileNav ? <X size={19} /> : <Menu size={19} />}</button><div className="mobile-col-brand"><CollectorMark size={24} /><b>ecova</b><span>/ collect</span></div><div className="collector-header-right"><button className={`online-toggle ${collectorOnline ? "online" : "offline"}`} onClick={toggleOnline}><i /> {collectorOnline ? "ONLINE" : "OFFLINE"}<span className="toggle-track"><span /></span></button><button className="col-notification" onClick={() => toast(notifications[0] ?? "No new notifications", { description: "Notifications reflect synchronized material-flow events." })}><CircleHelp size={17} /></button></div></header>
      <div className="collector-content"><div className="col-breadcrumb"><span>ECOVA</span><ChevronRight size={12} /><span>COLLECT</span><ChevronRight size={12} /><b>{viewNames[view].toUpperCase()}</b></div>{!collectorOnline && <div className="offline-banner"><WifiOff size={15} /><span><b>OFFLINE MODE</b> New requests unavailable. Previously loaded pickups remain accessible.</span></div>}{syncStatus === "degraded" && <div className="offline-banner" role="status"><WifiOff size={15} /><span><b>SYNC PAUSED</b> {dataError ?? "Latest backend data is unavailable."} Actions will not be marked complete until Ecova reconnects.</span></div>}
        {view === "overview" && <CollectorOverview requests={requests} active={active} routeStops={routeStops} earnings={collectorEarnings} online={collectorOnline} onRequest={openRequest} onActive={openActive} onQueue={() => setViewAndClose("queue")} />}
        {view === "queue" && <QueueView requests={requests} online={collectorOnline} onRequest={openRequest} />}
        {view === "routes" && <RoutesView stops={routeStops} />}
        {view === "earnings" && <EarningsView transactions={collectorEarnings} />}
        {view === "history" && <HistoryView pickups={pickups} onOpen={(pickup) => { setSelectedId(pickup.id); setSheet("active"); }} />}
      </div>
    </main>
    {sheet === "request" && selected && <RequestSheet pickup={selected} onClose={() => setSheet(null)} onAccept={async () => { await acceptPickup(selected.id); setSheet("active"); toast("Pickup accepted", { description: `${selected.id} is now assigned to your route.` }); }} />}
    {sheet === "active" && selected && <ActiveSheet pickup={selected} onClose={() => setSheet(null)} onArrive={async () => { await markArrived(selected.id); toast("Arrival recorded", { description: `${selected.id} is now ARRIVED in the shared record.` }); }} onCollect={async () => { await markCollected(selected.id); setSheet("verify"); }} onVerify={() => setSheet("verify")} onHub={async () => { await deliverToHub(selected.id); }} onRecycle={async () => { await confirmRecycling(selected.id); setSheet(null); }} disabled={isMutating} />}
    {sheet === "verify" && selected && <VerifySheet pickup={selected} weight={verifiedWeight} setWeight={setVerifiedWeight} condition={condition} setCondition={setCondition} proofFileName={proofFileName} onProofSelected={onProofSelected} onClose={() => setSheet(null)} onConfirm={completeVerification} disabled={isMutating} />}
  </div>;
}

function CollectorOverview({ requests, active, routeStops, earnings, online, onRequest, onActive, onQueue }: { requests: SharedPickup[]; active: SharedPickup | undefined; routeStops: SharedPickup[]; earnings: { amount: number }[]; online: boolean; onRequest: (pickup: SharedPickup) => void; onActive: (pickup: SharedPickup) => void; onQueue: () => void }) {
  const completed = pickupsForMetrics(routeStops, active);
  const loadedKg = completed.reduce((sum, pickup) => sum + (pickup.verifiedWeight ?? 0), 0);
  const capacity = Math.min(100, Math.round((loadedKg / 40) * 100));
  const totalEarnings = earnings.reduce((sum, transaction) => sum + transaction.amount, 0);
  return <section className="collector-overview"><div className="collector-welcome"><div><Kicker>GOOD EVENING · DEMO COLLECTOR</Kicker><h1>Keep the network<br /><em>moving.</em></h1><p>Review nearby collection requests, optimize your route, and verify material as it moves through Ecova.</p></div><div className="col-availability"><span><i className={online ? "dot-online" : "dot-offline"} /> {online ? "AVAILABLE FOR REQUESTS" : "OFFLINE"}</span><b>Route 07 · Ikeja</b></div></div><div className="col-metrics"><div className="col-metrics-head"><span>OPERATIONS SUMMARY</span><span className="col-demo"><i /> LIVE RECORD</span></div><div className="col-metrics-row"><ColMetric label="COMPLETED PICKUPS" value={String(completed.length)} detail="Persisted collection events" /><ColMetric label="VERIFIED MATERIAL" value={loadedKg.toFixed(1)} unit="KG" detail="Loaded from verified weights" /><ColMetric label="EARNINGS" value={totalEarnings.toLocaleString()} unit="ECO" detail="Recorded collector earnings" /><ColMetric label="CAPACITY" value={String(capacity)} unit="%" detail={`${loadedKg.toFixed(1)} KG / 40 KG`} capacity /></div></div><div className="collector-split"><section className="col-map-panel"><div className="col-panel-heading"><div><Kicker>ROUTE VIEW · DEMO</Kicker><h2>Today's collection zone.</h2></div><button onClick={onQueue}>Open queue <ArrowRight size={14} /></button></div><DemoMap stops={routeStops} /></section><section className="nearby-panel"><div className="col-panel-heading"><div><Kicker>NEARBY REQUESTS</Kicker><h2>Next on the network.</h2></div><button onClick={onQueue}>View all <ArrowRight size={14} /></button></div>{!online ? <div className="queue-offline"><WifiOff size={18} /><b>Requests paused offline.</b><span>Previously loaded pickups remain accessible.</span></div> : requests.length ? requests.slice(0, 3).map((pickup) => <RequestRow key={pickup.id} pickup={pickup} onClick={() => onRequest(pickup)} />) : <div className="queue-empty"><PackageCheck size={18} /><b>No new requests yet.</b><span>New Generator pickups will appear here.</span></div>}</section></div>{active && <section className="active-collection-strip"><div><Kicker>ACTIVE COLLECTION</Kicker><h2>{active.id}</h2><span>{active.material} · {active.estimatedWeight.toFixed(1)} KG EST.</span></div><div className="active-strip-status"><span className={`active-state active-${active.status.toLowerCase()}`}><i /> {active.status}</span><b>{active.location}</b></div><button onClick={() => onActive(active)}>Continue collection <ArrowRight size={15} /></button></section>}</section>;
}
function pickupsForMetrics(routeStops: SharedPickup[], active?: SharedPickup) { return [...routeStops, ...(active ? [active] : [])].filter((pickup, index, all) => all.findIndex((item) => item.id === pickup.id) === index && pickup.verifiedWeight !== undefined); }
function ColMetric({ label, value, unit, detail, capacity }: { label: string; value: string; unit?: string; detail: string; capacity?: boolean }) { return <div className="col-metric"><span>{label}</span><strong>{value} <small>{unit}</small></strong>{capacity ? <div className="capacity-bar"><i style={{ width: `${value}%` }} /></div> : null}<p>{detail}</p></div>; }
function DemoMap({ stops }: { stops: SharedPickup[] }) { return <div className="demo-map"><div className="map-road road-one" /><div className="map-road road-two" /><div className="map-road road-three" /><div className="map-block block-one" /><div className="map-block block-two" /><div className="map-block block-three" /><div className="map-block block-four" /><div className="map-label zone-label">COLLECTION ZONE 04</div><div className="map-current"><Navigation size={14} /><span>YOU</span></div>{stops.slice(0, 2).map((stop, index) => <button className={`map-stop map-stop-${index + 1}`} key={stop.id}><span>{index + 1}</span><small>{stop.id}</small></button>)}<div className="map-hub"><Recycle size={15} /><span>HUB 07</span></div><div className="map-legend"><span><i className="legend-you" /> YOUR LOCATION</span><span><i className="legend-pickup" /> PICKUP</span><span><i className="legend-active" /> ACTIVE</span><span><i className="legend-hub" /> RECYCLING HUB</span></div></div>; }
function RequestRow({ pickup, onClick }: { pickup: SharedPickup; onClick: () => void }) { return <button className="request-row" onClick={onClick}><div className="request-row-id"><b>{pickup.id}</b><small>{pickup.material.toUpperCase()}</small></div><div><span>WEIGHT</span><b>{pickup.estimatedWeight.toFixed(1)} KG EST.</b></div><div><span>DISTANCE</span><b>1.8 KM</b></div><div><span>WINDOW</span><b>{pickup.pickupWindow}</b></div><div className="request-reward"><span>REWARD</span><b>~{Math.round(pickup.estimatedWeight * 100)} ECO</b></div><ChevronRight size={15} /></button>; }
function QueueView({ requests, online, onRequest }: { requests: SharedPickup[]; online: boolean; onRequest: (pickup: SharedPickup) => void }) { return <section className="collector-page"><div className="collector-page-heading"><div><Kicker>COLLECT / PICKUP QUEUE</Kicker><h1>Requests that keep<br /><em>the route moving.</em></h1><p>Nearby Generator requests, ordered for the demo route.</p></div><span className={`queue-status ${online ? "queue-online" : "queue-offline-status"}`}><i /> {online ? "RECEIVING REQUESTS" : "OFFLINE"}</span></div>{online && requests.length ? <div className="queue-list">{requests.map((pickup) => <RequestRow key={pickup.id} pickup={pickup} onClick={() => onRequest(pickup)} />)}</div> : <div className="queue-empty queue-page-empty">{online ? <><PackageCheck size={22} /><b>No requests in the queue.</b><span>Switch to Generator and schedule a pickup to see it here.</span></> : <><WifiOff size={22} /><b>Requests unavailable offline.</b><span>Loaded route data remains available.</span></>}</div>}</section>; }
function RoutesView({ stops }: { stops: SharedPickup[] }) { return <section className="collector-page"><div className="collector-page-heading"><div><Kicker>COLLECT / TODAY'S ROUTE</Kicker><h1>A clear route<br /><em>through the city.</em></h1><p>Demo route planning only — not live GPS optimization.</p></div><div className="route-kpis"><span><b>8.6 KM</b> EST. DISTANCE</span><span><b>2H 40M</b> COLLECTION TIME</span></div></div><div className="route-plan"><div className="route-plan-line" />{(stops.length ? stops : [{ id: "PICKUP 01", material: "PET Plastic", estimatedWeight: 4.7 }, { id: "PICKUP 02", material: "Cardboard", estimatedWeight: 8.2 }, { id: "PICKUP 03", material: "Glass", estimatedWeight: 3.5 }] as SharedPickup[]).map((stop, index) => <div className="route-stop" key={stop.id}><div className="route-stop-dot">{String(index + 1).padStart(2, "0")}</div><div><span>PICKUP {String(index + 1).padStart(2, "0")}</span><b>{stop.id} · {stop.material}</b><small>{stop.estimatedWeight.toFixed(1)} KG EST. · ~{Math.round(stop.estimatedWeight * 100)} ECO</small></div><time>{index === 0 ? "14:00" : index === 1 ? "14:45" : "15:30"}</time></div>)}<div className="route-stop route-stop-hub"><div className="route-stop-dot"><Recycle size={14} /></div><div><span>DESTINATION</span><b>EC-HUB-07 · Sorting hub</b><small>Material handoff · Bay 02</small></div><time>16:12</time></div></div><div className="capacity-card"><div><Kicker>COLLECTOR CAPACITY</Kicker><h2>28.4 KG <small>/ 40 KG</small></h2></div><div className="large-capacity"><i style={{ width: "71%" }} /></div><span>71% CAPACITY · DEMO LOAD</span></div></section>; }
function EarningsView({ transactions }: { transactions: { id: string; pickupId: string; amount: number; item: string; date: string }[] }) { const earned = transactions.filter((transaction) => transaction.amount > 0); return <section className="collector-page"><div className="collector-page-heading"><div><Kicker>COLLECT / EARNINGS</Kicker><h1>Work that creates<br /><em>verified value.</em></h1><p>Transparent demo earnings based on verified material weight.</p></div><span className="col-demo"><i /> DEMO DATA</span></div><div className="earnings-grid"><div><span>TODAY</span><strong>1,840 <small>ECO</small></strong></div><div><span>THIS WEEK</span><strong>8,420 <small>ECO</small></strong></div><div><span>COMPLETED</span><strong>18 <small>PICKUPS</small></strong></div></div><div className="earnings-history"><div className="col-panel-heading"><div><Kicker>COLLECTOR TRANSACTIONS</Kicker><h2>Verified work, recorded.</h2></div><span className="demo-data"><i /> SEEDED VALUES</span></div>{earned.slice(0, 6).map((transaction) => <div className="earning-row" key={transaction.id}><div><b>{transaction.pickupId}</b><span>{transaction.item}</span></div><strong>+{transaction.amount} ECO</strong><time>{transaction.date}</time></div>)}</div></section>; }
function HistoryView({ pickups, onOpen }: { pickups: SharedPickup[]; onOpen: (pickup: SharedPickup) => void }) { return <section className="collector-page"><div className="collector-page-heading"><div><Kicker>COLLECT / HISTORY</Kicker><h1>Every collection<br /><em>leaves a record.</em></h1><p>Completed handoffs and verified reward history.</p></div></div><div className="history-list"><div className="history-head"><span>PICKUP</span><span>MATERIAL</span><span>WEIGHT</span><span>DATE</span><span>STATUS</span><span>REWARD</span><span /></div>{pickups.map((pickup) => <button className="history-row" key={pickup.id} onClick={() => onOpen(pickup)}><b>{pickup.id}</b><span>{pickup.material}</span><span>{pickup.verifiedWeight ? `${pickup.verifiedWeight.toFixed(2)} KG` : `${pickup.estimatedWeight.toFixed(1)} KG EST.`}</span><span>{pickup.date}</span><span className={`history-status history-${pickup.status.toLowerCase()}`}><i /> {pickup.status}</span><strong>{pickup.reward ? `+${pickup.reward} ECO` : "—"}</strong><ChevronRight size={15} /></button>)}</div></section>; }

function RequestSheet({ pickup, onClose, onAccept }: { pickup: SharedPickup; onClose: () => void; onAccept: () => void }) { return <div className="collector-sheet-backdrop"><aside className="collector-sheet request-sheet"><div className="sheet-heading"><div><Kicker>PICKUP REQUEST</Kicker><h2>{pickup.id}</h2></div><button onClick={onClose}><X size={19} /></button></div><div className="sheet-material"><PackageCheck size={21} /><span>{pickup.material}</span></div><div className="request-detail-grid"><div><span>ESTIMATED WEIGHT</span><b>{pickup.estimatedWeight.toFixed(1)} KG</b></div><div><span>PICKUP WINDOW</span><b>{pickup.pickupWindow}</b></div><div><span>LOCATION</span><b>{pickup.location}</b></div><div><span>ESTIMATED ROUTE</span><b>1.8 KM</b></div><div><span>ESTIMATED COLLECTION REWARD</span><b className="eco-green">~{Math.round(pickup.estimatedWeight * 100)} ECO</b></div></div><div className="sheet-mini-map"><div className="mini-map-line" /><MapPin size={19} /><span>Demo pickup location</span></div><div className="sheet-actions"><button className="sheet-decline" onClick={onClose}>Decline</button><button className="collector-primary" onClick={onAccept}>Accept pickup <ArrowRight size={15} /></button></div></aside></div>; }
function ActiveSheet({ pickup, onClose, onArrive, onCollect, onVerify, onHub, onRecycle, disabled }: { pickup: SharedPickup; onClose: () => void; onArrive: () => void; onCollect: () => void; onVerify: () => void; onHub: () => void; onRecycle: () => void; disabled: boolean }) {
  const statusIndex = ["ASSIGNED", "ARRIVED", "COLLECTED", "VERIFIED", "DELIVERED"].indexOf(pickup.status);
  const actions = {
    ASSIGNED: <><Kicker>NEXT ACTION</Kicker><h3>Navigate to the pickup location.</h3><p>Follow the demo route to {pickup.location}. This is not live GPS navigation.</p><button className="collector-primary" disabled={disabled} onClick={onArrive}>{disabled ? "Saving..." : "Mark arrived"} <ArrowRight size={15} /></button></>,
    ARRIVED: <><Kicker>READY TO COLLECT</Kicker><h3>Collector arrived.</h3><p className="technical-time">ARRIVED · {pickup.arrivedAt ?? "BACKEND TIME PENDING"}</p><button className="collector-primary" disabled={disabled} onClick={onCollect}>{disabled ? "Saving..." : "Mark collected"} <ArrowRight size={15} /></button></>,
    COLLECTED: <><Kicker>MATERIAL COLLECTED</Kicker><h3>Ready to verify the weight.</h3><p>Record the actual measurement before the reward is calculated.</p><button className="collector-primary" disabled={disabled} onClick={onVerify}>Verify weight <ArrowRight size={15} /></button></>,
    VERIFIED: <><Kicker>VERIFIED COLLECTION</Kicker><h3>Deliver this same pickup to the Hub.</h3><p>EC-HUB-07 will receive {pickup.verifiedWeight?.toFixed(2)} KG before recycling is confirmed.</p><button className="collector-primary" disabled={disabled} onClick={onHub}>{disabled ? "Saving..." : "Confirm Hub receipt"} <ArrowRight size={15} /></button></>,
    DELIVERED: <><Kicker>HUB RECEIVED</Kicker><h3>Confirm recycling for {pickup.id}.</h3><p>The Hub has received this material. This final action appends the recycling record.</p><button className="collector-primary" disabled={disabled} onClick={onRecycle}>{disabled ? "Saving..." : "Confirm recycling"} <ArrowRight size={15} /></button></>,
  }[pickup.status as "ASSIGNED" | "ARRIVED" | "COLLECTED" | "VERIFIED" | "DELIVERED"];
  return <div className="collector-sheet-backdrop"><aside className="collector-sheet active-sheet"><div className="sheet-heading"><div><Kicker>ACTIVE COLLECTION</Kicker><h2>{pickup.id}</h2></div><button onClick={onClose} aria-label="Close collection sheet"><X size={19} /></button></div><div className="active-sheet-material"><div><span>{pickup.material.toUpperCase()}</span><b>{pickup.verifiedWeight ? `${pickup.verifiedWeight.toFixed(2)} KG VERIFIED` : `${pickup.estimatedWeight.toFixed(1)} KG EST.`}</b><small>{pickup.location}</small></div><Truck size={29} /></div><div className="collection-progress">{[["NAVIGATE", Navigation], ["ARRIVED", MapPin], ["COLLECTED", PackageCheck], ["VERIFY WEIGHT", ShieldCheck], ["HUB RECEIVED", Recycle]].map(([label, Icon], index) => { const StepIcon = Icon as typeof Navigation; return <div className={index <= statusIndex ? "progress-done" : ""} key={label as string}><span><StepIcon size={14} /></span><b>{label as string}</b>{index < 4 && <i />}</div>; })}</div><div className="active-action">{actions}</div></aside></div>;
}

function VerifySheet({ pickup, weight, setWeight, condition, setCondition, proofFileName, onProofSelected, onClose, onConfirm, disabled }: { pickup: SharedPickup; weight: number; setWeight: (value: number) => void; condition: "Clean" | "Mostly clean" | "Mixed" | "Contaminated"; setCondition: (value: "Clean" | "Mostly clean" | "Mixed" | "Contaminated") => void; proofFileName?: string; onProofSelected: (file: File) => void; onClose: () => void; onConfirm: () => void; disabled: boolean }) { const reward = Number.isFinite(weight) && weight > 0 ? Math.round(weight * 100) : 0; return <div className="collector-sheet-backdrop"><aside className="collector-sheet verify-sheet"><div className="sheet-heading"><div><Kicker>03 / WEIGHT VERIFICATION</Kicker><h2>{pickup.id}</h2></div><button onClick={onClose} aria-label="Close verification sheet"><X size={19} /></button></div><div className="verify-intro"><h3>Record the actual weight.</h3><p>Rewards are calculated from verified weight. The AI classifier cannot determine final reward value.</p></div><div className="verify-input-wrap"><span>VERIFIED WEIGHT</span><div><input type="number" min="0.01" max="100" step="0.1" value={Number.isFinite(weight) ? weight : ""} onChange={(event) => setWeight(Number(event.target.value))} aria-label="Verified weight in kilograms" /><b>KG</b></div><small>Estimated weight: {pickup.estimatedWeight.toFixed(2)} KG · Maximum 100 KG</small></div><div className="reward-calculation"><span>DEMO REWARD RATE</span><div><b>{weight.toFixed(2)} KG VERIFIED</b><span>× 100 ECO / KG</span><strong>{reward} ECO</strong></div><small>Demonstration rule only — not a real-world pricing guarantee.</small></div><div className="condition-block"><span>MATERIAL CONDITION</span><div>{["Clean", "Mostly clean", "Mixed", "Contaminated"].map((item) => <button className={condition === item ? "condition-active" : ""} key={item} onClick={() => setCondition(item as typeof condition)}>{condition === item && <Check size={12} />}{item}</button>)}</div></div><label className="proof-upload"><Upload size={16} /><span><b>{proofFileName ? "Proof selected" : "Upload proof"}</b><small>{proofFileName ?? "Optional scale or collection image · stored with verification"}</small></span><ChevronRight size={14} /><input type="file" accept="image/png,image/jpeg,image/gif,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file && file.size <= 8 * 1024 * 1024) onProofSelected(file); else if (file) toast.error("Choose an image smaller than 8 MB."); }} style={{ width: 120, height: 36, opacity: 0.01, position: "absolute", cursor: "pointer" }} /></label><div className="sheet-actions"><button className="sheet-decline" onClick={onClose} disabled={disabled}>Cancel</button><button className="collector-primary" disabled={disabled || !Number.isFinite(weight) || weight <= 0 || weight > 100} onClick={onConfirm}>{disabled ? "Saving verification..." : "Confirm weight"} <ArrowRight size={15} /></button></div></aside></div>; }

export default Collector;
